apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  labels:
    app: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: reservation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            # ================= APP =================
            - name: NODE_ENV
              value: production
            - name: APP_PORT
              value: "3000"

            # ================= MYSQL =================
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: reservation_db
            - name: DB_USER
              value: root         # <-- root user
            - name: DB_PASSWORD
              value: ""           # <-- vide pour MySQL sans password

            # ================= EUREKA =================
            - name: EUREKA_HOST
              value: discovery-service
            - name: EUREKA_PORT
              value: "8761"
            - name: EUREKA_SERVICE_PATH
              value: /eureka/apps/
            - name: EUREKA_APP_NAME
              value: RESERVATION-SERVICE
            - name: EUREKA_INSTANCE_HOSTNAME
              value: reservation-service
            - name: EUREKA_INSTANCE_PORT
              value: "3000"

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  selector:
    app: reservation-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
