apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: reservation-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 7
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  type: LoadBalancer
  selector:
    app: reservation-service
  ports:
    - port: 3000
      targetPort: 3000