apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-hoteliere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-hoteliere
  template:
    metadata:
      labels:
        app: gestion-hoteliere
    spec:
      containers:
        - name: gestion-hoteliere
          image: gestion_hoteliere:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-hoteliere
spec:
  selector:
    app: gestion-hoteliere
  ports:
    - protocol: TCP
      port: 4200    # exposed to user
      targetPort: 80  # port inside container
  type: LoadBalancer
