apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: client-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            # ================= APP =================
            - name: FLASK_ENV
              value: production
            - name: APP_PORT
              value: "8088"
            # ================= MYSQL =================
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "gestion_client"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""

            # ================= EUREKA =================
            - name: EUREKA_HOST
              value: "discovery-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: EUREKA_SERVICE_PATH
              value: /eureka/apps/
            - name: EUREKA_APP_NAME
              value: CLIENT-SERVICE
            - name: EUREKA_INSTANCE_HOSTNAME
              value: client-service
            - name: EUREKA_INSTANCE_PORT
              value: "8088"
          volumeMounts:
            - name: public-key-volume
              mountPath: /app/keys
          livenessProbe:
              httpGet:
                path: /health
                port: 8088
              initialDelaySeconds: 30
              periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /health
                port: 8088
              initialDelaySeconds: 10
              periodSeconds: 10
      volumes:
        - name: public-key-volume
          configMap:
            name: client-publickey
            items:
              - key: publickey.pem
                path: publickey.pem
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: LoadBalancer
